# Generated by Django 5.2.12 on 2026-03-25 17:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.IntegerField(unique=True, verbose_name='Flight ID')),
                ('airline', models.CharField(default='Unknown', max_length=100)),
                ('status', models.CharField(choices=[('landing', 'Landing'), ('takeoff', 'Takeoff'), ('StandBy', 'Stand By'), ('Landed', 'Landed'), ('Departed', 'Departed'), ('Cancelled', 'Cancelled')], default='StandBy', max_length=20)),
                ('emergency', models.BooleanField(default=False)),
                ('time', models.IntegerField(default=0, help_text='Scheduled time in minutes past midnight (0–1439)')),
                ('runway_id', models.IntegerField(default=0, verbose_name='Runway ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['time', '-emergency'],
            },
        ),
        migrations.CreateModel(
            name='FlightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='port.flight')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runway_id', models.IntegerField(unique=True, verbose_name='Runway ID')),
                ('status', models.CharField(choices=[('free', 'Free'), ('busy', 'Busy')], default='free', max_length=10)),
                ('assigned_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_runway', to='port.flight')),
            ],
        ),
    ]
