# Generated by Django 5.2.5 on 2026-03-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['date_day', 'time', '-emergency']},
        ),
        migrations.AddField(
            model_name='flight',
            name='date_day',
            field=models.IntegerField(default=1, help_text='Day of the current year (1–365). Cannot be earlier than today.', verbose_name='Day of Year'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='runway_id',
            field=models.IntegerField(default=1, help_text='Runway number (1–5)', verbose_name='Runway ID'),
        ),
    ]
